//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvProject.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCvEntities : DbContext
    {
        public DbCvEntities()
            : base("name=DbCvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<about> about { get; set; }
        public virtual DbSet<certificates> certificates { get; set; }
        public virtual DbSet<contact> contact { get; set; }
        public virtual DbSet<experiences> experiences { get; set; }
        public virtual DbSet<hobies> hobies { get; set; }
        public virtual DbSet<login> login { get; set; }
        public virtual DbSet<skills> skills { get; set; }
        public virtual DbSet<trainings> trainings { get; set; }
    }
}
